spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://119.23.228.252:3306/jiuluoblog?useUnicode=true&characterEncoding=utf8
    username: root
    password: 980714
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

server:
  port: 8089
